%%{init: {"state":{"nodeSpacing":28,"rankSpacing":32,"padding":6}}}%%
stateDiagram-v2
  [*] --> Disponivel : cadastro do item
  Disponivel --> EmUso : movimentacao<br/>para setor/sala
  Disponivel --> Emprestado : emprestimo<br/>com prazo
  Emprestado --> Disponivel : devolucao<br/>registrada
  Emprestado --> EmAtraso : passou a<br/>data prevista
  EmAtraso --> Disponivel : devolucao<br/>registrada
  EmUso --> Manutencao : envio para<br/>manutencao
  Manutencao --> Disponivel : retorno da<br/>manutencao
  EmUso --> Disponivel : retorno ao<br/>estoque
  Disponivel --> Baixado : baixa do item
  EmUso --> Baixado : baixa do item
  Baixado --> [*]

  note right of Baixado
    Item baixado rejeita
    qualquer nova
    movimentacao (RN013)
  end note
